---
title: "Notes on Using Git"
author: "Ben Duffey"
date: "July 20, 2015"
output: pdf_document
---

The GitHub repo that contains the code that generated these notes is located at <https://github.com/biduffey/Git-Notes>.

# How to Use Git

## Installing local Git To run with Rstudio
  * Install git software locally from the website. Make sure to choose the option where it is added to PATH  
    * If you can't open the git bash shell from R-Studio, then it is still not in PATH
  * To add it to the path, go to:  
      
      *computer*  
      *->  system properties*  
      *->  advanced system settings*     
      *->  environmental variables*  
      *->  change path variable to include the git executable folder*  

## Git hub account
  * Create an account on Github.com
  * Create a repo that will will use to share your work
  * Later on, you will sync your local work to this account. 

## Creating a new local repository
  * A local repository is just a folder that git knows to keep an eye on. 
  * Open the shell in Rstudio (if not already open).
  * Use bash commands *{pwd, ls, cd, etc.}* to navigate to the directory you want your files.
  * Run the command *git init*. This will convert the directory you are in into a git repo. 
  * Edit whatever R scripts or markdown documents are desired.

## Tracking 
  * Git needs to know which programs to monitor/track
  * Run *Git add ./<document>* to track a document in the repo
    *In general, I think you only want to add 1 program to be tracked. Keeps it simple and is easier to sync later on with git up. 
  * To untrack a file, type *git rm -r --cached <document>*
    * To untrack everything, type *git rm -r --cached ./*
  * To view a list of tracked files: *git ls-files*

## Committing
  **Git commit* a checkpoint to which you can revert and compare future changes.  
    * Save changes in your documents. Run *git commit*.
    * Message screen will come up … add something (should be in yellow font)
      * Press esc, type “:wq”, press enter

## Pushing to Git hub
  * **Git Push https://github.com/biduffey/nameofrep.git**
    * ->username/password
    * There cannot be any files in github that are not already tracked and committed in the repo.  If there are you must actually pull those files into the local git before pulling. 

## Pulling
  * **Git pull https://github.com/biduffey/nameofrep.git**
    * If there are any duplicate files, I think you must move, rename, or delete the one in the local repository. 

## Forking
  * A fork is just a copy
  * The is really just used to experiment, or make a non-commital change, by making the change to a copy - instead of the real deal. 
  * To fork a repo, type *git clone https://github.com/biduffey/<<nameofrepyouwanttoclone.git>> nameofnewfolder*
	
## Resources
  * Super helpful website: http://readwrite.com/2013/10/02/github-for-beginners-part-2 
  * https://help.github.com/articles/fork-a-repo/
