#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  1 12:19:41 2019

@author: benduffey
"""

import airflow
from airflow import models, settings
from airflow.contrib.auth.backends.password_auth import PasswordUser
user = PasswordUser(models.User())
user.username = 'marketing_flow'
user.email = 'fred.astaire@gmail.com'
user.password = '<password>'
session = settings.Session()
session.add(user)
session.commit()
session.close()
exit() 
